# Generated by Django 5.2.16 on 2026-08-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('release', models.DateField()),
                ('steam_url', models.URLField()),
                ('image_url', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
